/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class common_Utilities */

#ifndef _Included_common_Utilities
#define _Included_common_Utilities
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     common_Utilities
 * Method:    realToString
 * Signature: (D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_common_Utilities_realToString
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     common_Utilities
 * Method:    byteToString
 * Signature: (B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_common_Utilities_byteToString
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     common_Utilities
 * Method:    str2d
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_common_Utilities_str2d
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
